version: '3.8'

services:
  # PostgreSQL Database for n8n
  postgres:
    image: postgres:15
    container_name: n8n-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_secure_password_2024_enhanced
      POSTGRES_NON_ROOT_USER: n8n
      POSTGRES_NON_ROOT_PASSWORD: n8n_secure_password_2024_enhanced
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U n8n -d n8n']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - n8n-network

  # n8n Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-main
    restart: unless-stopped
    environment:
      # Database Configuration
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n_secure_password_2024_enhanced
      DB_POSTGRESDB_SCHEMA: public
      
      # Security Configuration
      N8N_ENCRYPTION_KEY: 'your_32_character_encryption_key_here_123456'
      N8N_USER_MANAGEMENT_DISABLED: 'false'
      N8N_SECURE_COOKIE: 'false'
      
      # Basic Configuration
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://localhost:5678
      GENERIC_TIMEZONE: Asia/Shanghai
      
      # Features
      N8N_METRICS: 'true'
      N8N_LOG_LEVEL: info
      N8N_PUBLIC_API_DISABLED: 'false'
      N8N_VERSION_NOTIFICATIONS_ENABLED: 'false'
      N8N_RUNNERS_ENABLED: 'true'
      N8N_AI_ENABLED: 'true'
      
      # Performance
      NODE_OPTIONS: '--max-old-space-size=2048'
      
      # API Configuration
      N8N_API_KEY_PREFIX: 'n8n_api_'
      
      # 火鸟门户集成配置
      HUONIAO_BASE_URL: ${HUONIAO_BASE_URL:-https://hawaiihub.net}
      HUONIAO_API_ENDPOINT: ${HUONIAO_API_ENDPOINT:-https://hawaiihub.net/include/ajax.php}
      HUONIAO_SESSION_ID: ${HUONIAO_SESSION_ID}
      HUONIAO_USERNAME: ${HUONIAO_USERNAME}
      HUONIAO_PASSWORD: ${HUONIAO_PASSWORD}
      
      # Notion集成配置
      NOTION_API_TOKEN: ${NOTION_API_TOKEN}
      NOTION_DATABASE_ID: ${NOTION_DATABASE_ID}
      NOTION_VERSION: ${NOTION_VERSION:-2022-06-28}
      
      # AI服务配置
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.openai.com/v1}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-3.5-turbo}
      
      # 监控和告警配置
      WEBHOOK_ALERT_URL: ${WEBHOOK_ALERT_URL}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      
      # 安全配置
      GATEWAY_SECRET_KEY: ${GATEWAY_SECRET_KEY:-huoniao_gateway_secret_2025}
      ENABLE_SECURITY: ${ENABLE_SECURITY:-true}
      
      # 性能配置
      BATCH_SIZE: ${BATCH_SIZE:-5}
      RATE_LIMIT: ${RATE_LIMIT:-10}
      RETRY_ATTEMPTS: ${RETRY_ATTEMPTS:-3}
      RETRY_DELAY: ${RETRY_DELAY:-2000}
      
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/.n8n/workflows
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:5678/healthz']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
    networks:
      - n8n-network

volumes:
  postgres_data:
    driver: local
  n8n_data:
    driver: local

networks:
  n8n-network:
    driver: bridge